const baseAttractions = [
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Parkwide / Entertainment",
    "name": "Festival of Fantasy Parade",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 1,
    "uncertainty": "Star/color visible; yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Parkwide / Entertainment",
    "name": "Disney Starlight Parade",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 2,
    "uncertainty": "Star/color visible; yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Main Street, U.S.A.",
    "name": "Ride the Train",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 3,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Main Street, U.S.A.",
    "name": "Shopping",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 4,
    "uncertainty": "Not a ride; included because starred."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "Prince Charming Regal Carrousel",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 5,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "Peter Pan's Flight",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 6,
    "uncertainty": ""
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "It's a small world",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 7,
    "uncertainty": ""
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "Mad Tea Party",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 8,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "Dumbo the Flying Elephant",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 9,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "Mickey's PhilharMagic",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 10,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "The Many Adventures of Winnie the Pooh",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 11,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "Barnstormer",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "35 inch height note shown.",
    "status": "Active",
    "order": 12,
    "uncertainty": ""
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "Under the Sea: Journey of the Little Mermaid",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 13,
    "uncertainty": "Yellow not in user legend; name read from sheet."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "Seven Dwarfs Mine Train",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "38 inch height note shown.",
    "status": "Active",
    "order": 14,
    "uncertainty": "Color appears purple/blue; booking interpretation likely."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Fantasyland",
    "name": "Cheshire Cafe",
    "color": "Green",
    "meaning": "Must do / food stop",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 15,
    "uncertainty": "Not a ride; included because starred."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Tomorrowland",
    "name": "Tomorrowland Speedway",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "32 inch height note shown.",
    "status": "Active",
    "order": 16,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Tomorrowland",
    "name": "Space Mountain",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "44 inch height note shown.",
    "status": "Active",
    "order": 17,
    "uncertainty": ""
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Tomorrowland",
    "name": "Buzz Lightyear's Space Ranger Spin",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 18,
    "uncertainty": ""
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Tomorrowland",
    "name": "TRON Lightcycle / Run",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "48 inch height note shown.",
    "status": "Active",
    "order": 19,
    "uncertainty": "Purple/blue mark suggests booking; confirm."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Tomorrowland",
    "name": "Astro Orbiter",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 20,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Tomorrowland",
    "name": "Laugh Floor",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 21,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Tomorrowland",
    "name": "PeopleMover",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "Handwritten note nearby: \u201cHave an [unclear] is between booking...\u201d",
    "status": "Active",
    "order": 22,
    "uncertainty": "Pink/purple note partially unreadable."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Liberty Square",
    "name": "Haunted Mansion",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 23,
    "uncertainty": ""
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Liberty Square",
    "name": "Hall of Presidents",
    "color": "Red/Pink",
    "meaning": "Skip",
    "booking": false,
    "notes": "Marked with skip-style note.",
    "status": "Skip",
    "order": 24,
    "uncertainty": "Starred but skipped; handwriting partially unclear."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Frontierland",
    "name": "Tiana's Bayou Adventure",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "40 inch height note shown.",
    "status": "Active",
    "order": 25,
    "uncertainty": "Color appears purple/blue; confirm booking status."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Frontierland",
    "name": "Big Thunder Mountain Railroad",
    "color": "Orange/Yellow",
    "meaning": "If time or special category",
    "booking": false,
    "notes": "40 inch height note shown.",
    "status": "Active",
    "order": 26,
    "uncertainty": "Orange/yellow shade uncertain."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Frontierland",
    "name": "Country Bear Musical Jamboree",
    "color": "Red",
    "meaning": "Skip",
    "booking": false,
    "notes": "",
    "status": "Skip",
    "order": 27,
    "uncertainty": "Appears red star/mark; verify."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Frontierland",
    "name": "Pecos Bill Tall Tale Inn",
    "color": "Green",
    "meaning": "Must do / food stop",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 28,
    "uncertainty": "Not a ride; included because starred."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Adventureland",
    "name": "Pirates of the Caribbean",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 29,
    "uncertainty": ""
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Adventureland",
    "name": "Jungle Cruise",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 30,
    "uncertainty": ""
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Adventureland",
    "name": "Enchanted Tiki Room",
    "color": "Red/Pink",
    "meaning": "Skip",
    "booking": false,
    "notes": "",
    "status": "Skip",
    "order": 31,
    "uncertainty": "Appears marked skip."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Adventureland",
    "name": "Swiss Family Treehouse",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 32,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 1,
    "park": "Magic Kingdom",
    "land": "Adventureland",
    "name": "The Magic Carpets of Aladdin",
    "color": "Red/Pink",
    "meaning": "Skip or low priority",
    "booking": false,
    "notes": "",
    "status": "Skip",
    "order": 33,
    "uncertainty": "Looks red/pink; verify whether skip."
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Parkwide / Entertainment",
    "name": "Fantasmic!",
    "color": "Orange/Yellow",
    "meaning": "If time or special category",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 1,
    "uncertainty": "Orange/yellow shade uncertain."
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Hollywood Blvd.",
    "name": "Mickey & Minnie's Runaway Railway",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 2,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Echo Lake",
    "name": "Star Tours",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 3,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Echo Lake",
    "name": "For the First Time in Forever: Frozen Sing-Along",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 4,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Echo Lake",
    "name": "Indiana Jones Epic Stunt Spectacular",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 5,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Echo Lake",
    "name": "Meet Olaf",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 6,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Sunset Blvd.",
    "name": "The Twilight Zone Tower of Terror",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "40 inch height note shown.",
    "status": "Active",
    "order": 7,
    "uncertainty": "Booking color appears purple/blue."
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Sunset Blvd.",
    "name": "Beauty and the Beast Live on Stage",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 8,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Animation Courtyard",
    "name": "The Little Mermaid Show",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 9,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Toy Story Land",
    "name": "Toy Story Mania",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "",
    "status": "Active",
    "order": 10,
    "uncertainty": "Color appears purple/blue."
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Toy Story Land",
    "name": "Alien Swirling Saucers",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "32 inch height note shown.",
    "status": "Active",
    "order": 11,
    "uncertainty": "Color appears purple/blue."
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Toy Story Land",
    "name": "Slinky Dog Dash",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "38 inch height note shown.",
    "status": "Active",
    "order": 12,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Toy Story Land",
    "name": "Woody's Lunch Box",
    "color": "Green",
    "meaning": "Must do / food stop",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 13,
    "uncertainty": "Not a ride; included because starred."
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Star Wars: Galaxy's Edge",
    "name": "Millennium Falcon: Smugglers Run",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "38 inch height note shown.",
    "status": "Active",
    "order": 14,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "Hollywood Studios",
    "land": "Star Wars: Galaxy's Edge",
    "name": "Star Wars: Rise of the Resistance",
    "color": "Green/Purple",
    "meaning": "Must do, possible booking/special attention",
    "booking": true,
    "notes": "40 inch height note shown. Pink handwritten note nearby partially unclear.",
    "status": "Active",
    "order": 15,
    "uncertainty": "Booking note/marking unclear; verify."
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Celebration",
    "name": "Spaceship Earth",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "",
    "status": "Active",
    "order": 16,
    "uncertainty": "Color appears purple/blue."
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Nature",
    "name": "The Seas with Nemo and Friends",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "",
    "status": "Active",
    "order": 17,
    "uncertainty": "Color appears purple/blue."
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Nature",
    "name": "Living with the Land",
    "color": "Orange/Yellow",
    "meaning": "If time or special category",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 18,
    "uncertainty": "Orange/yellow shade uncertain."
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Nature",
    "name": "Soarin'",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "40 inch height note shown.",
    "status": "Active",
    "order": 19,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Nature",
    "name": "Journey of Water",
    "color": "Yellow",
    "meaning": "If time / lower priority",
    "booking": false,
    "notes": "Moana themed area.",
    "status": "Active",
    "order": 20,
    "uncertainty": "Yellow not in user legend."
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Nature",
    "name": "Turtle Talk with Crush",
    "color": "Yellow/Orange",
    "meaning": "If time or special category",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 21,
    "uncertainty": "Name partially near bottom of land section; color unclear."
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Discovery",
    "name": "Guardians of the Galaxy: Cosmic Rewind",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "42 inch height note shown.",
    "status": "Active",
    "order": 22,
    "uncertainty": "Booking likely."
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Discovery",
    "name": "Mission: SPACE",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "40 inch height note shown; handwritten note mentions orange/strong intensity.",
    "status": "Active",
    "order": 23,
    "uncertainty": "Color and note partially unclear."
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Showcase",
    "name": "Gran Fiesta Tour Starring The Three Caballeros",
    "color": "Yellow/Orange",
    "meaning": "If time or special category",
    "booking": false,
    "notes": "Mexico.",
    "status": "Active",
    "order": 24,
    "uncertainty": "Color uncertain."
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Showcase",
    "name": "Frozen Ever After",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "Norway.",
    "status": "Active",
    "order": 25,
    "uncertainty": ""
  },
  {
    "day": 2,
    "park": "EPCOT",
    "land": "World Showcase",
    "name": "Remy's Ratatouille Adventure",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "France.",
    "status": "Active",
    "order": 26,
    "uncertainty": ""
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Discovery Island",
    "name": "Take a Photo with the Tree of Life",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 1,
    "uncertainty": ""
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Discovery Island",
    "name": "It's Tough to be a Bug",
    "color": "Red/Pink",
    "meaning": "Skip",
    "booking": false,
    "notes": "Marked with skip-style handwritten note.",
    "status": "Skip",
    "order": 2,
    "uncertainty": "Attraction may be replaced by Zootopia show depending timing; verify."
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Discovery Island",
    "name": "Zootopia: Better Zoogether",
    "color": "Green",
    "meaning": "Must do",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 3,
    "uncertainty": ""
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Pandora - The World of Avatar",
    "name": "Na'vi River Journey",
    "color": "Green/Purple",
    "meaning": "Must do, possible booking/special attention",
    "booking": true,
    "notes": "",
    "status": "Active",
    "order": 4,
    "uncertainty": "Both green and purple/blue markings appear nearby."
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Pandora - The World of Avatar",
    "name": "Avatar Flight of Passage",
    "color": "Purple/Blue + Green",
    "meaning": "Booking or special attention; must do",
    "booking": true,
    "notes": "44 inch height note shown.",
    "status": "Active",
    "order": 5,
    "uncertainty": "Booking likely."
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Africa",
    "name": "Kilimanjaro Safaris",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "",
    "status": "Active",
    "order": 6,
    "uncertainty": "Color appears purple/blue."
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Africa",
    "name": "Festival of the Lion King",
    "color": "Orange/Yellow",
    "meaning": "If time or special category",
    "booking": false,
    "notes": "",
    "status": "Active",
    "order": 7,
    "uncertainty": "Orange/yellow shade uncertain."
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Africa",
    "name": "Wildlife Express Train",
    "color": "Orange/Yellow + Red",
    "meaning": "Uncertain / possible skip",
    "booking": false,
    "notes": "",
    "status": "Uncertain",
    "order": 8,
    "uncertainty": "Contains yellow/orange star and red X-like mark; verify whether skip."
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Africa",
    "name": "Meet Goofy",
    "color": "Red/Pink",
    "meaning": "Skip or note",
    "booking": false,
    "notes": "Pink note says skip/unclear.",
    "status": "Skip",
    "order": 9,
    "uncertainty": "Handwritten mark unclear."
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Asia",
    "name": "Expedition Everest",
    "color": "Purple/Blue",
    "meaning": "Booking or special attention",
    "booking": true,
    "notes": "44 inch height note shown.",
    "status": "Active",
    "order": 10,
    "uncertainty": "Booking/special color appears purple/blue."
  },
  {
    "day": 3,
    "park": "Animal Kingdom",
    "land": "Asia",
    "name": "Feathered Friends in Flight",
    "color": "Red/Pink",
    "meaning": "Skip",
    "booking": false,
    "notes": "",
    "status": "Skip",
    "order": 11,
    "uncertainty": "Appears red/pink star/mark; verify."
  }
];

