const baseAttractions = 
[
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Parkwide / Entertainment",
        "name":  "Festival of Fantasy Parade",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  1,
        "uncertainty":  "Star/color visible; yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Parkwide / Entertainment",
        "name":  "Disney Starlight Parade",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  2,
        "uncertainty":  "Star/color visible; yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Main Street, U.S.A.",
        "name":  "Ride the Train",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  3,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Main Street, U.S.A.",
        "name":  "Shopping",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  4,
        "uncertainty":  "Not a ride; included because starred."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Prince Charming Regal Carrousel",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  5,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Peter Pan\u0027s Flight",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "It\u0027s a small world",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  7,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Mad Tea Party",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  8,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Dumbo the Flying Elephant",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  9,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Mickey\u0027s PhilharMagic",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  10,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "The Many Adventures of Winnie the Pooh",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  11,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Barnstormer",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "35 in",
        "notes":  "",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Under the Sea: Journey of the Little Mermaid",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  13,
        "uncertainty":  "Yellow not in user legend; name read from sheet."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Seven Dwarfs Mine Train",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "38 in",
        "notes":  "",
        "status":  "Active",
        "order":  14,
        "uncertainty":  "Color appears purple/blue; booking interpretation likely."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Cheshire Cafe",
        "color":  "Green",
        "meaning":  "Must do / food stop",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  15,
        "uncertainty":  "Not a ride; included because starred."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Tomorrowland Speedway",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "32 in",
        "notes":  "",
        "status":  "Active",
        "order":  16,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Space Mountain",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "44 in",
        "notes":  "",
        "status":  "Active",
        "order":  17,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Buzz Lightyear\u0027s Space Ranger Spin",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  18,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "TRON Lightcycle / Run",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "48 in",
        "notes":  "",
        "status":  "Active",
        "order":  19,
        "uncertainty":  "Purple/blue mark suggests booking; confirm."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Astro Orbiter",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  20,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Laugh Floor",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  21,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "PeopleMover",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "Handwritten note nearby: ?Have an [unclear] is between booking...?",
        "status":  "Active",
        "order":  22,
        "uncertainty":  "Pink/purple note partially unreadable."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Liberty Square",
        "name":  "Haunted Mansion",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  23,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Liberty Square",
        "name":  "Hall of Presidents",
        "color":  "Red/Pink",
        "meaning":  "Skip",
        "booking":  false,
        "height":  "",
        "notes":  "Marked with skip-style note.",
        "status":  "Skip",
        "order":  24,
        "uncertainty":  "Starred but skipped; handwriting partially unclear."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Frontierland",
        "name":  "Tiana\u0027s Bayou Adventure",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "40 in",
        "notes":  "",
        "status":  "Active",
        "order":  25,
        "uncertainty":  "Color appears purple/blue; confirm booking status."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Frontierland",
        "name":  "Big Thunder Mountain Railroad",
        "color":  "Orange/Yellow",
        "meaning":  "If time or special category",
        "booking":  false,
        "height":  "38 in",
        "notes":  "",
        "status":  "Active",
        "order":  26,
        "uncertainty":  "Orange/yellow shade uncertain."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Frontierland",
        "name":  "Country Bear Musical Jamboree",
        "color":  "Red",
        "meaning":  "Skip",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Skip",
        "order":  27,
        "uncertainty":  "Appears red star/mark; verify."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Frontierland",
        "name":  "Pecos Bill Tall Tale Inn",
        "color":  "Green",
        "meaning":  "Must do / food stop",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  28,
        "uncertainty":  "Not a ride; included because starred."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "Pirates of the Caribbean",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  29,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "Jungle Cruise",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  30,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "Enchanted Tiki Room",
        "color":  "Red/Pink",
        "meaning":  "Skip",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Skip",
        "order":  31,
        "uncertainty":  "Appears marked skip."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "Swiss Family Treehouse",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  32,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "The Magic Carpets of Aladdin",
        "color":  "Red/Pink",
        "meaning":  "Skip or low priority",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Skip",
        "order":  33,
        "uncertainty":  "Looks red/pink; verify whether skip."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Parkwide / Entertainment",
        "name":  "Fantasmic!",
        "color":  "Orange/Yellow",
        "meaning":  "If time or special category",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  1,
        "uncertainty":  "Orange/yellow shade uncertain."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Hollywood Blvd.",
        "name":  "Mickey \u0026 Minnie\u0027s Runaway Railway",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  2,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Echo Lake",
        "name":  "Star Tours",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "40 in",
        "notes":  "",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Echo Lake",
        "name":  "For the First Time in Forever: Frozen Sing-Along",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  4,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Echo Lake",
        "name":  "Indiana Jones Epic Stunt Spectacular",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  5,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Echo Lake",
        "name":  "Meet Olaf",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Sunset Blvd.",
        "name":  "The Twilight Zone Tower of Terror",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "40 in",
        "notes":  "",
        "status":  "Active",
        "order":  7,
        "uncertainty":  "Booking color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Sunset Blvd.",
        "name":  "Beauty and the Beast Live on Stage",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  8,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Animation Courtyard",
        "name":  "The Little Mermaid Show",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  9,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Toy Story Land",
        "name":  "Toy Story Mania",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  10,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Toy Story Land",
        "name":  "Alien Swirling Saucers",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "32 in",
        "notes":  "",
        "status":  "Active",
        "order":  11,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Toy Story Land",
        "name":  "Slinky Dog Dash",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "38 in",
        "notes":  "",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Toy Story Land",
        "name":  "Woody\u0027s Lunch Box",
        "color":  "Green",
        "meaning":  "Must do / food stop",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  13,
        "uncertainty":  "Not a ride; included because starred."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Star Wars: Galaxy\u0027s Edge",
        "name":  "Millennium Falcon: Smugglers Run",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "38 in",
        "notes":  "",
        "status":  "Active",
        "order":  14,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Star Wars: Galaxy\u0027s Edge",
        "name":  "Star Wars: Rise of the Resistance",
        "color":  "Green/Purple",
        "meaning":  "Must do, possible booking/special attention",
        "booking":  true,
        "height":  "40 in",
        "notes":  "Pink handwritten note nearby partially unclear.",
        "status":  "Active",
        "order":  15,
        "uncertainty":  "Booking note/marking unclear; verify."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Celebration",
        "name":  "Spaceship Earth",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  16,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "The Seas with Nemo and Friends",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  17,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "Living with the Land",
        "color":  "Orange/Yellow",
        "meaning":  "If time or special category",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  18,
        "uncertainty":  "Orange/yellow shade uncertain."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "Soarin\u0027",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "40 in",
        "notes":  "",
        "status":  "Active",
        "order":  19,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "Journey of Water",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "",
        "notes":  "Moana themed area.",
        "status":  "Active",
        "order":  20,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "Turtle Talk with Crush",
        "color":  "Yellow/Orange",
        "meaning":  "If time or special category",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  21,
        "uncertainty":  "Name partially near bottom of land section; color unclear."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Discovery",
        "name":  "Guardians of the Galaxy: Cosmic Rewind",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "42 in",
        "notes":  "",
        "status":  "Active",
        "order":  22,
        "uncertainty":  "Booking likely."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Discovery",
        "name":  "Mission: SPACE",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "40 in",
        "notes":  "handwritten note mentions orange/strong intensity.",
        "status":  "Active",
        "order":  23,
        "uncertainty":  "Color and note partially unclear."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Showcase",
        "name":  "Gran Fiesta Tour Starring The Three Caballeros",
        "color":  "Yellow/Orange",
        "meaning":  "If time or special category",
        "booking":  false,
        "height":  "",
        "notes":  "Mexico.",
        "status":  "Active",
        "order":  24,
        "uncertainty":  "Color uncertain."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Showcase",
        "name":  "Frozen Ever After",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "Norway.",
        "status":  "Active",
        "order":  25,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Showcase",
        "name":  "Remy\u0027s Ratatouille Adventure",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "France.",
        "status":  "Active",
        "order":  26,
        "uncertainty":  ""
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Discovery Island",
        "name":  "Take a Photo with the Tree of Life",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  1,
        "uncertainty":  ""
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Discovery Island",
        "name":  "It\u0027s Tough to be a Bug",
        "color":  "Red/Pink",
        "meaning":  "Skip",
        "booking":  false,
        "height":  "",
        "notes":  "Marked with skip-style handwritten note.",
        "status":  "Skip",
        "order":  2,
        "uncertainty":  "Attraction may be replaced by Zootopia show depending timing; verify."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Discovery Island",
        "name":  "Zootopia: Better Zoogether",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Pandora - The World of Avatar",
        "name":  "Na\u0027vi River Journey",
        "color":  "Green/Purple",
        "meaning":  "Must do, possible booking/special attention",
        "booking":  true,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  4,
        "uncertainty":  "Both green and purple/blue markings appear nearby."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Pandora - The World of Avatar",
        "name":  "Avatar Flight of Passage",
        "color":  "Purple/Blue + Green",
        "meaning":  "Booking or special attention; must do",
        "booking":  true,
        "height":  "44 in",
        "notes":  "",
        "status":  "Active",
        "order":  5,
        "uncertainty":  "Booking likely."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Africa",
        "name":  "Kilimanjaro Safaris",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  6,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Africa",
        "name":  "Festival of the Lion King",
        "color":  "Orange/Yellow",
        "meaning":  "If time or special category",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Active",
        "order":  7,
        "uncertainty":  "Orange/yellow shade uncertain."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Africa",
        "name":  "Wildlife Express Train",
        "color":  "Orange/Yellow + Red",
        "meaning":  "Uncertain / possible skip",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Uncertain",
        "order":  8,
        "uncertainty":  "Contains yellow/orange star and red X-like mark; verify whether skip."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Africa",
        "name":  "Meet Goofy",
        "color":  "Red/Pink",
        "meaning":  "Skip or note",
        "booking":  false,
        "height":  "",
        "notes":  "Pink note says skip/unclear.",
        "status":  "Skip",
        "order":  9,
        "uncertainty":  "Handwritten mark unclear."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Asia",
        "name":  "Expedition Everest",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "height":  "44 in",
        "notes":  "",
        "status":  "Active",
        "order":  10,
        "uncertainty":  "Booking/special color appears purple/blue."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Asia",
        "name":  "Feathered Friends in Flight",
        "color":  "Red/Pink",
        "meaning":  "Skip",
        "booking":  false,
        "height":  "",
        "notes":  "",
        "status":  "Skip",
        "order":  11,
        "uncertainty":  "Appears red/pink star/mark; verify."
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "Celestial Park",
        "name":  "Enter Through Celestial Park",
        "color":  "Yellow",
        "meaning":  "Arrival / orientation",
        "booking":  false,
        "height":  "",
        "notes":  "Use as regroup and route-planning zone before splitting to portals.",
        "status":  "Active",
        "order":  1,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "Super Nintendo World",
        "name":  "Mario Kart: Bowser\u0027s Challenge",
        "color":  "Green",
        "meaning":  "Highest priority",
        "booking":  false,
        "height":  "40 in",
        "notes":  "Do immediately at rope drop if possible.",
        "status":  "Active",
        "order":  2,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "Super Nintendo World",
        "name":  "Mine-Cart Madness",
        "color":  "Green",
        "meaning":  "Highest priority",
        "booking":  false,
        "height":  "40 in",
        "notes":  "Major family coaster headliner; expect long waits.",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "Super Nintendo World",
        "name":  "Power-Up Band Activities",
        "color":  "Orange",
        "meaning":  "Optional interactive upgrade",
        "booking":  true,
        "height":  "",
        "notes":  "Worth it only if planning extended Nintendo exploration.",
        "status":  "Active",
        "order":  4,
        "uncertainty":  "Requires additional purchase."
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "Super Nintendo World",
        "name":  "Yoshi\u0027s Adventure",
        "color":  "Yellow",
        "meaning":  "If time / family ride",
        "booking":  false,
        "height":  "34 in",
        "notes":  "supervising companion required under 48 inches. Good rest ride after Mario Kart area congestion.",
        "status":  "Active",
        "order":  5,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "The Wizarding World of Harry Potter - Ministry of Magic",
        "name":  "Harry Potter and the Battle at the Ministry",
        "color":  "Green",
        "meaning":  "Highest priority",
        "booking":  false,
        "height":  "40 in",
        "notes":  "Major flagship attraction; prioritize before afternoon crowds.",
        "status":  "Active",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "The Wizarding World of Harry Potter - Ministry of Magic",
        "name":  "Le Cirque Arcanus",
        "color":  "Green",
        "meaning":  "Must do show",
        "booking":  false,
        "height":  "",
        "notes":  "Good midday cooldown and seated break.",
        "status":  "Active",
        "order":  7,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "The Wizarding World of Harry Potter - Ministry of Magic",
        "name":  "Wizarding Paris Exploration",
        "color":  "Yellow",
        "meaning":  "Atmosphere / optional",
        "booking":  false,
        "height":  "",
        "notes":  "Use for food, wand interactions, and visual breaks.",
        "status":  "Active",
        "order":  8,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "How to Train Your Dragon - Isle of Berk",
        "name":  "Hiccup\u0027s Wing Gliders",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "40 in",
        "notes":  "Strong family coaster and good pacing ride.",
        "status":  "Active",
        "order":  9,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "How to Train Your Dragon - Isle of Berk",
        "name":  "The Untrainable Dragon",
        "color":  "Green",
        "meaning":  "Must do show",
        "booking":  false,
        "height":  "",
        "notes":  "Recommended recharge point during hottest hours.",
        "status":  "Active",
        "order":  10,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "How to Train Your Dragon - Isle of Berk",
        "name":  "Fyre Drill",
        "color":  "Orange",
        "meaning":  "Water attraction / optional",
        "booking":  false,
        "height":  "Supervise under 48 in",
        "notes":  "Can soak riders; better later in day.",
        "status":  "Active",
        "order":  11,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "How to Train Your Dragon - Isle of Berk",
        "name":  "Dragon Racer\u0027s Rally",
        "color":  "Orange",
        "meaning":  "Thrill optional",
        "booking":  false,
        "height":  "48 in",
        "notes":  "More intense spinning attraction; not for everyone.",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "Dark Universe",
        "name":  "Monsters Unchained: The Frankenstein Experiment",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "48 in",
        "notes":  "Top-tier dark ride and one of park priorities.",
        "status":  "Active",
        "order":  13,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "Dark Universe",
        "name":  "Curse of the Werewolf",
        "color":  "Orange",
        "meaning":  "Thrill optional",
        "booking":  false,
        "height":  "40 in",
        "notes":  "Good secondary thrill ride if nearby.",
        "status":  "Active",
        "order":  14,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "Celestial Park",
        "name":  "Stardust Racers",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "48 in",
        "notes":  "",
        "status":  "Active",
        "order":  15,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Epic Universe",
        "land":  "Celestial Park",
        "name":  "Constellation Carousel",
        "color":  "Yellow",
        "meaning":  "If time / atmosphere",
        "booking":  false,
        "height":  "",
        "notes":  "Best experienced after sunset lighting activates.",
        "status":  "Active",
        "order":  16,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Port of Entry",
        "name":  "Early Entry Positioning",
        "color":  "Green",
        "meaning":  "Strategic start",
        "booking":  false,
        "height":  "",
        "notes":  "Move directly toward Hogsmeade at park open.",
        "status":  "Active",
        "order":  1,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "The Wizarding World of Harry Potter - Hogsmeade",
        "name":  "Hagrid\u0027s Magical Creatures Motorbike Adventure",
        "color":  "Green",
        "meaning":  "Highest priority",
        "booking":  false,
        "height":  "48 in",
        "notes":  "Absolute rope-drop target; highest operational priority in park.",
        "status":  "Active",
        "order":  2,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "The Wizarding World of Harry Potter - Hogsmeade",
        "name":  "Harry Potter and the Forbidden Journey",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "48 in",
        "notes":  "Best immediately after Hagrid\u0027s before crowds build.",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "The Wizarding World of Harry Potter - Hogsmeade",
        "name":  "Flight of the Hippogriff",
        "color":  "Yellow",
        "meaning":  "If time / family coaster",
        "booking":  false,
        "height":  "36 in",
        "notes":  "Good nearby filler if wait is low.",
        "status":  "Active",
        "order":  4,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "The Wizarding World of Harry Potter - Hogsmeade",
        "name":  "Hogwarts Express - Hogsmeade Station",
        "color":  "Purple",
        "meaning":  "Park-to-park ticket required",
        "booking":  true,
        "height":  "Supervise under 48 in",
        "notes":  "Requires park-to-park admission.",
        "status":  "Active",
        "order":  5,
        "uncertainty":  "Requires park-to-park admission."
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Jurassic Park",
        "name":  "Jurassic World VelociCoaster",
        "color":  "Green",
        "meaning":  "Highest priority",
        "booking":  false,
        "height":  "51 in",
        "notes":  "Top-tier coaster; prioritize before afternoon waits spike.",
        "status":  "Active",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Jurassic Park",
        "name":  "Jurassic Park River Adventure",
        "color":  "Orange",
        "meaning":  "Water ride / optional",
        "booking":  false,
        "height":  "42 in",
        "notes":  "Good afternoon ride when heat rises.",
        "status":  "Active",
        "order":  7,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Jurassic Park",
        "name":  "Pteranodon Flyers",
        "color":  "Yellow",
        "meaning":  "Child-dependent",
        "booking":  true,
        "height":  "36-56 in",
        "notes":  "guests over 56 inches must ride with a qualifying child. Eligibility rules may vary.",
        "status":  "Active",
        "order":  8,
        "uncertainty":  "Eligibility rules may vary."
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Marvel Super Hero Island",
        "name":  "The Amazing Adventures of Spider-Man",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "40 in",
        "notes":  "One of the best balanced family thrill rides.",
        "status":  "Active",
        "order":  9,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Marvel Super Hero Island",
        "name":  "The Incredible Hulk Coaster",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "54 in",
        "notes":  "High intensity coaster; prioritize if thrill-focused group.",
        "status":  "Active",
        "order":  10,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Marvel Super Hero Island",
        "name":  "Doctor Doom\u0027s Fearfall",
        "color":  "Orange",
        "meaning":  "Thrill optional",
        "booking":  false,
        "height":  "52 in",
        "notes":  "Quick experience if nearby and wait low.",
        "status":  "Active",
        "order":  11,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Toon Lagoon",
        "name":  "Dudley Do-Right\u0027s Ripsaw Falls",
        "color":  "Orange",
        "meaning":  "Water ride / optional",
        "booking":  false,
        "height":  "44 in",
        "notes":  "Very wet; only ride if okay staying soaked.",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Toon Lagoon",
        "name":  "Popeye \u0026 Bluto\u0027s Bilge-Rat Barges",
        "color":  "Orange",
        "meaning":  "Water ride / optional",
        "booking":  false,
        "height":  "42 in",
        "notes":  "Most soaking attraction in park.",
        "status":  "Active",
        "order":  13,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Skull Island",
        "name":  "Skull Island: Reign of Kong",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "height":  "36 in",
        "notes":  "Good shaded queue and indoor cooldown.",
        "status":  "Active",
        "order":  14,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Seuss Landing",
        "name":  "High in the Sky Seuss Trolley Train Ride",
        "color":  "Yellow",
        "meaning":  "If time / scenic",
        "booking":  false,
        "height":  "36 in",
        "notes":  "Good park overview and decompression ride.",
        "status":  "Active",
        "order":  15,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Islands of Adventure",
        "land":  "Seuss Landing",
        "name":  "The Cat in the Hat",
        "color":  "Yellow",
        "meaning":  "If time / family ride",
        "booking":  false,
        "height":  "36 in",
        "notes":  "Useful lower-intensity reset attraction.",
        "status":  "Active",
        "order":  16,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Production Central",
        "name":  "TRANSFORMERS: The Ride-3D",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "40 in",
        "notes":  "Strong early-day attraction before simulator queues rise.",
        "status":  "Active",
        "order":  1,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Production Central",
        "name":  "Despicable Me Minion Mayhem",
        "color":  "Yellow",
        "meaning":  "If time / family simulator",
        "booking":  false,
        "height":  "40 in",
        "notes":  "Can become crowded early with families.",
        "status":  "Active",
        "order":  2,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "New York",
        "name":  "Revenge of the Mummy",
        "color":  "Green",
        "meaning":  "Highest priority",
        "booking":  false,
        "height":  "48 in",
        "notes":  "One of park\u0027s best attractions; prioritize early or late.",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "San Francisco",
        "name":  "Fast \u0026 Furious: Supercharged",
        "color":  "Red",
        "meaning":  "Skip",
        "booking":  false,
        "height":  "40 in",
        "notes":  "Low-value time investment unless walk-on.",
        "status":  "Skip",
        "order":  4,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "The Wizarding World of Harry Potter - Diagon Alley",
        "name":  "Harry Potter and the Escape from Gringotts",
        "color":  "Green",
        "meaning":  "Highest priority",
        "booking":  false,
        "height":  "42 in",
        "notes":  "Core headliner attraction; high thematic value.",
        "status":  "Active",
        "order":  5,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "The Wizarding World of Harry Potter - Diagon Alley",
        "name":  "Diagon Alley Exploration",
        "color":  "Green",
        "meaning":  "Must do atmosphere",
        "booking":  false,
        "height":  "",
        "notes":  "Prioritize wand spots, dragon fire, and themed food.",
        "status":  "Active",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "The Wizarding World of Harry Potter - Diagon Alley",
        "name":  "Hogwarts Express - King\u0027s Cross Station",
        "color":  "Purple",
        "meaning":  "Park-to-park ticket required",
        "booking":  true,
        "height":  "Supervise under 48 in",
        "notes":  "Requires park-to-park admission.",
        "status":  "Active",
        "order":  7,
        "uncertainty":  "Requires park-to-park admission."
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "World Expo",
        "name":  "Men in Black Alien Attack",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "height":  "42 in",
        "notes":  "Excellent repeatable shooter attraction.",
        "status":  "Active",
        "order":  8,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Springfield USA",
        "name":  "The Simpsons Ride",
        "color":  "Yellow",
        "meaning":  "If time / fan-dependent",
        "booking":  false,
        "height":  "40 in",
        "notes":  "Motion-heavy simulator; skip if prone to sickness.",
        "status":  "Active",
        "order":  9,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Hollywood",
        "name":  "The Bourne Stuntacular",
        "color":  "Green",
        "meaning":  "Must do show",
        "booking":  false,
        "height":  "",
        "notes":  "Top-tier seated break with excellent effects.",
        "status":  "Active",
        "order":  10,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Hollywood",
        "name":  "Universal Orlando\u0027s Horror Make-Up Show",
        "color":  "Yellow",
        "meaning":  "If time / older kids",
        "booking":  false,
        "height":  "",
        "notes":  "Funny and worthwhile if timing lines up.",
        "status":  "Active",
        "order":  11,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Woody Woodpecker\u0027s KidZone",
        "name":  "E.T. Adventure",
        "color":  "Yellow",
        "meaning":  "Classic / nostalgic",
        "booking":  false,
        "height":  "34 in",
        "notes":  "Good slower-paced dark ride break.",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Minion Land",
        "name":  "Illumination\u0027s Villain-Con Minion Blast",
        "color":  "Yellow",
        "meaning":  "If time / interactive",
        "booking":  false,
        "height":  "Supervise under 48 in",
        "notes":  "Best if line remains short.",
        "status":  "Active",
        "order":  13,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Minion Land",
        "name":  "Minion Cafe",
        "color":  "Orange",
        "meaning":  "Food stop",
        "booking":  false,
        "height":  "",
        "notes":  "Useful lunch reset point with indoor seating.",
        "status":  "Active",
        "order":  14,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Hollywood",
        "name":  "DreamWorks Land",
        "color":  "Yellow",
        "meaning":  "Kids area / optional",
        "booking":  false,
        "height":  "",
        "notes":  "Best for younger children or energy reset.",
        "status":  "Active",
        "order":  15,
        "uncertainty":  ""
    }
]
;
