const baseAttractions = 
[
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Parkwide / Entertainment",
        "name":  "Festival of Fantasy Parade",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  1,
        "uncertainty":  "Star/color visible; yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Parkwide / Entertainment",
        "name":  "Disney Starlight Parade",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  2,
        "uncertainty":  "Star/color visible; yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Main Street, U.S.A.",
        "name":  "Ride the Train",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  3,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Main Street, U.S.A.",
        "name":  "Shopping",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  4,
        "uncertainty":  "Not a ride; included because starred."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Prince Charming Regal Carrousel",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  5,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Peter Pan\u0027s Flight",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "It\u0027s a small world",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  7,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Mad Tea Party",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  8,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Dumbo the Flying Elephant",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  9,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Mickey\u0027s PhilharMagic",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  10,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "The Many Adventures of Winnie the Pooh",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  11,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Barnstormer",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "35 inch height note shown.",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Under the Sea: Journey of the Little Mermaid",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  13,
        "uncertainty":  "Yellow not in user legend; name read from sheet."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Seven Dwarfs Mine Train",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "38 inch height note shown.",
        "status":  "Active",
        "order":  14,
        "uncertainty":  "Color appears purple/blue; booking interpretation likely."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Fantasyland",
        "name":  "Cheshire Cafe",
        "color":  "Green",
        "meaning":  "Must do / food stop",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  15,
        "uncertainty":  "Not a ride; included because starred."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Tomorrowland Speedway",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "32 inch height note shown.",
        "status":  "Active",
        "order":  16,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Space Mountain",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "44 inch height note shown.",
        "status":  "Active",
        "order":  17,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Buzz Lightyear\u0027s Space Ranger Spin",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  18,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "TRON Lightcycle / Run",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "48 inch height note shown.",
        "status":  "Active",
        "order":  19,
        "uncertainty":  "Purple/blue mark suggests booking; confirm."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Astro Orbiter",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  20,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "Laugh Floor",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  21,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Tomorrowland",
        "name":  "PeopleMover",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Handwritten note nearby: “Have an [unclear] is between booking...”",
        "status":  "Active",
        "order":  22,
        "uncertainty":  "Pink/purple note partially unreadable."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Liberty Square",
        "name":  "Haunted Mansion",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  23,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Liberty Square",
        "name":  "Hall of Presidents",
        "color":  "Red/Pink",
        "meaning":  "Skip",
        "booking":  false,
        "notes":  "Marked with skip-style note.",
        "status":  "Skip",
        "order":  24,
        "uncertainty":  "Starred but skipped; handwriting partially unclear."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Frontierland",
        "name":  "Tiana\u0027s Bayou Adventure",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "40 inch height note shown.",
        "status":  "Active",
        "order":  25,
        "uncertainty":  "Color appears purple/blue; confirm booking status."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Frontierland",
        "name":  "Big Thunder Mountain Railroad",
        "color":  "Orange/Yellow",
        "meaning":  "If time or special category",
        "booking":  false,
        "notes":  "40 inch height note shown.",
        "status":  "Active",
        "order":  26,
        "uncertainty":  "Orange/yellow shade uncertain."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Frontierland",
        "name":  "Country Bear Musical Jamboree",
        "color":  "Red",
        "meaning":  "Skip",
        "booking":  false,
        "notes":  "",
        "status":  "Skip",
        "order":  27,
        "uncertainty":  "Appears red star/mark; verify."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Frontierland",
        "name":  "Pecos Bill Tall Tale Inn",
        "color":  "Green",
        "meaning":  "Must do / food stop",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  28,
        "uncertainty":  "Not a ride; included because starred."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "Pirates of the Caribbean",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  29,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "Jungle Cruise",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  30,
        "uncertainty":  ""
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "Enchanted Tiki Room",
        "color":  "Red/Pink",
        "meaning":  "Skip",
        "booking":  false,
        "notes":  "",
        "status":  "Skip",
        "order":  31,
        "uncertainty":  "Appears marked skip."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "Swiss Family Treehouse",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  32,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  1,
        "park":  "Magic Kingdom",
        "land":  "Adventureland",
        "name":  "The Magic Carpets of Aladdin",
        "color":  "Red/Pink",
        "meaning":  "Skip or low priority",
        "booking":  false,
        "notes":  "",
        "status":  "Skip",
        "order":  33,
        "uncertainty":  "Looks red/pink; verify whether skip."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Parkwide / Entertainment",
        "name":  "Fantasmic!",
        "color":  "Orange/Yellow",
        "meaning":  "If time or special category",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  1,
        "uncertainty":  "Orange/yellow shade uncertain."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Hollywood Blvd.",
        "name":  "Mickey \u0026 Minnie\u0027s Runaway Railway",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  2,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Echo Lake",
        "name":  "Star Tours",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Echo Lake",
        "name":  "For the First Time in Forever: Frozen Sing-Along",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  4,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Echo Lake",
        "name":  "Indiana Jones Epic Stunt Spectacular",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  5,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Echo Lake",
        "name":  "Meet Olaf",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Sunset Blvd.",
        "name":  "The Twilight Zone Tower of Terror",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "40 inch height note shown.",
        "status":  "Active",
        "order":  7,
        "uncertainty":  "Booking color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Sunset Blvd.",
        "name":  "Beauty and the Beast Live on Stage",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  8,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Animation Courtyard",
        "name":  "The Little Mermaid Show",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  9,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Toy Story Land",
        "name":  "Toy Story Mania",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "",
        "status":  "Active",
        "order":  10,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Toy Story Land",
        "name":  "Alien Swirling Saucers",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "32 inch height note shown.",
        "status":  "Active",
        "order":  11,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Toy Story Land",
        "name":  "Slinky Dog Dash",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "38 inch height note shown.",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Toy Story Land",
        "name":  "Woody\u0027s Lunch Box",
        "color":  "Green",
        "meaning":  "Must do / food stop",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  13,
        "uncertainty":  "Not a ride; included because starred."
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Star Wars: Galaxy\u0027s Edge",
        "name":  "Millennium Falcon: Smugglers Run",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "38 inch height note shown.",
        "status":  "Active",
        "order":  14,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "Hollywood Studios",
        "land":  "Star Wars: Galaxy\u0027s Edge",
        "name":  "Star Wars: Rise of the Resistance",
        "color":  "Green/Purple",
        "meaning":  "Must do, possible booking/special attention",
        "booking":  true,
        "notes":  "40 inch height note shown. Pink handwritten note nearby partially unclear.",
        "status":  "Active",
        "order":  15,
        "uncertainty":  "Booking note/marking unclear; verify."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Celebration",
        "name":  "Spaceship Earth",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "",
        "status":  "Active",
        "order":  16,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "The Seas with Nemo and Friends",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "",
        "status":  "Active",
        "order":  17,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "Living with the Land",
        "color":  "Orange/Yellow",
        "meaning":  "If time or special category",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  18,
        "uncertainty":  "Orange/yellow shade uncertain."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "Soarin\u0027",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "40 inch height note shown.",
        "status":  "Active",
        "order":  19,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "Journey of Water",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "Moana themed area.",
        "status":  "Active",
        "order":  20,
        "uncertainty":  "Yellow not in user legend."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Nature",
        "name":  "Turtle Talk with Crush",
        "color":  "Yellow/Orange",
        "meaning":  "If time or special category",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  21,
        "uncertainty":  "Name partially near bottom of land section; color unclear."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Discovery",
        "name":  "Guardians of the Galaxy: Cosmic Rewind",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "42 inch height note shown.",
        "status":  "Active",
        "order":  22,
        "uncertainty":  "Booking likely."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Discovery",
        "name":  "Mission: SPACE",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "40 inch height note shown; handwritten note mentions orange/strong intensity.",
        "status":  "Active",
        "order":  23,
        "uncertainty":  "Color and note partially unclear."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Showcase",
        "name":  "Gran Fiesta Tour Starring The Three Caballeros",
        "color":  "Yellow/Orange",
        "meaning":  "If time or special category",
        "booking":  false,
        "notes":  "Mexico.",
        "status":  "Active",
        "order":  24,
        "uncertainty":  "Color uncertain."
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Showcase",
        "name":  "Frozen Ever After",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Norway.",
        "status":  "Active",
        "order":  25,
        "uncertainty":  ""
    },
    {
        "day":  2,
        "park":  "EPCOT",
        "land":  "World Showcase",
        "name":  "Remy\u0027s Ratatouille Adventure",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "France.",
        "status":  "Active",
        "order":  26,
        "uncertainty":  ""
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Discovery Island",
        "name":  "Take a Photo with the Tree of Life",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  1,
        "uncertainty":  ""
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Discovery Island",
        "name":  "It\u0027s Tough to be a Bug",
        "color":  "Red/Pink",
        "meaning":  "Skip",
        "booking":  false,
        "notes":  "Marked with skip-style handwritten note.",
        "status":  "Skip",
        "order":  2,
        "uncertainty":  "Attraction may be replaced by Zootopia show depending timing; verify."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Discovery Island",
        "name":  "Zootopia: Better Zoogether",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Pandora - The World of Avatar",
        "name":  "Na\u0027vi River Journey",
        "color":  "Green/Purple",
        "meaning":  "Must do, possible booking/special attention",
        "booking":  true,
        "notes":  "",
        "status":  "Active",
        "order":  4,
        "uncertainty":  "Both green and purple/blue markings appear nearby."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Pandora - The World of Avatar",
        "name":  "Avatar Flight of Passage",
        "color":  "Purple/Blue + Green",
        "meaning":  "Booking or special attention; must do",
        "booking":  true,
        "notes":  "44 inch height note shown.",
        "status":  "Active",
        "order":  5,
        "uncertainty":  "Booking likely."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Africa",
        "name":  "Kilimanjaro Safaris",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "",
        "status":  "Active",
        "order":  6,
        "uncertainty":  "Color appears purple/blue."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Africa",
        "name":  "Festival of the Lion King",
        "color":  "Orange/Yellow",
        "meaning":  "If time or special category",
        "booking":  false,
        "notes":  "",
        "status":  "Active",
        "order":  7,
        "uncertainty":  "Orange/yellow shade uncertain."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Africa",
        "name":  "Wildlife Express Train",
        "color":  "Orange/Yellow + Red",
        "meaning":  "Uncertain / possible skip",
        "booking":  false,
        "notes":  "",
        "status":  "Uncertain",
        "order":  8,
        "uncertainty":  "Contains yellow/orange star and red X-like mark; verify whether skip."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Africa",
        "name":  "Meet Goofy",
        "color":  "Red/Pink",
        "meaning":  "Skip or note",
        "booking":  false,
        "notes":  "Pink note says skip/unclear.",
        "status":  "Skip",
        "order":  9,
        "uncertainty":  "Handwritten mark unclear."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Asia",
        "name":  "Expedition Everest",
        "color":  "Purple/Blue",
        "meaning":  "Booking or special attention",
        "booking":  true,
        "notes":  "44 inch height note shown.",
        "status":  "Active",
        "order":  10,
        "uncertainty":  "Booking/special color appears purple/blue."
    },
    {
        "day":  3,
        "park":  "Animal Kingdom",
        "land":  "Asia",
        "name":  "Feathered Friends in Flight",
        "color":  "Red/Pink",
        "meaning":  "Skip",
        "booking":  false,
        "notes":  "",
        "status":  "Skip",
        "order":  11,
        "uncertainty":  "Appears red/pink star/mark; verify."
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Port of Entry",
        "name":  "Arrive / Photos / First Stop",
        "color":  "Yellow",
        "meaning":  "Arrival / optional",
        "booking":  false,
        "notes":  "Good place to regroup and set route mode.",
        "status":  "Active",
        "order":  1,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Marvel Super Hero Island",
        "name":  "The Amazing Adventures of Spider-Man",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Classic top-tier simulator dark ride.",
        "status":  "Active",
        "order":  2,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Marvel Super Hero Island",
        "name":  "The Incredible Hulk Coaster",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "High thrill coaster; intense launch/inversions.",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Marvel Super Hero Island",
        "name":  "Doctor Doom\u0027s Fearfall",
        "color":  "Orange",
        "meaning":  "Thrill optional",
        "booking":  false,
        "notes":  "Short drop tower; good if thrill group wants it.",
        "status":  "Active",
        "order":  4,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Toon Lagoon",
        "name":  "Dudley Do-Right\u0027s Ripsaw Falls",
        "color":  "Orange",
        "meaning":  "Water ride / optional",
        "booking":  false,
        "notes":  "You may get soaked; better when hot.",
        "status":  "Active",
        "order":  5,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Toon Lagoon",
        "name":  "Popeye \u0026 Bluto\u0027s Bilge-Rat Barges",
        "color":  "Orange",
        "meaning":  "Water ride / optional",
        "booking":  false,
        "notes":  "Very wet; do only if okay being soaked.",
        "status":  "Active",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Skull Island",
        "name":  "Skull Island: Reign of Kong",
        "color":  "Yellow",
        "meaning":  "If time / lower priority",
        "booking":  false,
        "notes":  "Good filler if nearby and wait is low.",
        "status":  "Active",
        "order":  7,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Jurassic Park",
        "name":  "Jurassic World VelociCoaster",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Elite thrill coaster; prioritize early or late.",
        "status":  "Active",
        "order":  8,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Jurassic Park",
        "name":  "Jurassic Park River Adventure",
        "color":  "Orange",
        "meaning":  "Water ride / priority if hot",
        "booking":  false,
        "notes":  "May get wet; strong family/thrill balance.",
        "status":  "Active",
        "order":  9,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Jurassic Park",
        "name":  "Pteranodon Flyers",
        "color":  "Yellow",
        "meaning":  "Child-dependent",
        "booking":  true,
        "notes":  "Usually limited to kids with adults; check rules/wait.",
        "status":  "Active",
        "order":  10,
        "uncertainty":  "Eligibility can vary by child/adult pairing."
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "The Wizarding World of Harry Potter - Hogsmeade",
        "name":  "Hagrid\u0027s Magical Creatures Motorbike Adventure",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Highest priority; often long wait.",
        "status":  "Active",
        "order":  11,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "The Wizarding World of Harry Potter - Hogsmeade",
        "name":  "Harry Potter and the Forbidden Journey",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Major themed dark ride; can cause motion sickness.",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "The Wizarding World of Harry Potter - Hogsmeade",
        "name":  "Flight of the Hippogriff",
        "color":  "Yellow",
        "meaning":  "If time / family coaster",
        "booking":  false,
        "notes":  "Good quick family coaster if wait is low.",
        "status":  "Active",
        "order":  13,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "The Wizarding World of Harry Potter - Hogsmeade",
        "name":  "Hogwarts Express - Hogsmeade Station",
        "color":  "Purple",
        "meaning":  "Park-to-park ticket required",
        "booking":  true,
        "notes":  "Use only if hopping to Universal Studios Florida.",
        "status":  "Active",
        "order":  14,
        "uncertainty":  "Requires valid park-to-park admission."
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Seuss Landing",
        "name":  "The Cat in the Hat",
        "color":  "Yellow",
        "meaning":  "If time / family ride",
        "booking":  false,
        "notes":  "Good low-intensity family dark ride.",
        "status":  "Active",
        "order":  15,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Seuss Landing",
        "name":  "High in the Sky Seuss Trolley Train Ride",
        "color":  "Yellow",
        "meaning":  "If time / scenic",
        "booking":  false,
        "notes":  "Nice overhead view; do if nearby.",
        "status":  "Active",
        "order":  16,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Seuss Landing",
        "name":  "One Fish Two Fish Red Fish Blue Fish",
        "color":  "Yellow",
        "meaning":  "If time / kids",
        "booking":  false,
        "notes":  "Simple spinner; skip if short on time.",
        "status":  "Active",
        "order":  17,
        "uncertainty":  ""
    },
    {
        "day":  4,
        "park":  "Islands of Adventure",
        "land":  "Seuss Landing",
        "name":  "Caro-Seuss-el",
        "color":  "Yellow",
        "meaning":  "If time / kids",
        "booking":  false,
        "notes":  "Good for younger kids only.",
        "status":  "Active",
        "order":  18,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Celestial Park",
        "name":  "Stardust Racers",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Major dual-launch coaster; prioritize if thrill riders.",
        "status":  "Active",
        "order":  1,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Celestial Park",
        "name":  "Constellation Carousel",
        "color":  "Yellow",
        "meaning":  "If time / atmosphere",
        "booking":  false,
        "notes":  "Better at night if schedule allows.",
        "status":  "Active",
        "order":  2,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Celestial Park",
        "name":  "Astronomica",
        "color":  "Yellow",
        "meaning":  "If time / atmosphere",
        "booking":  false,
        "notes":  "Walkthrough/play fountain area; good filler.",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Super Nintendo World",
        "name":  "Mario Kart: Bowser\u0027s Challenge",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Signature interactive ride; prioritize early.",
        "status":  "Active",
        "order":  4,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Super Nintendo World",
        "name":  "Yoshi\u0027s Adventure",
        "color":  "Yellow",
        "meaning":  "If time / family ride",
        "booking":  false,
        "notes":  "Good for younger kids and Nintendo fans.",
        "status":  "Active",
        "order":  5,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Super Nintendo World",
        "name":  "Mine-Cart Madness",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Family/thrill coaster; likely high demand.",
        "status":  "Active",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Super Nintendo World",
        "name":  "Power-Up Band Activities",
        "color":  "Orange",
        "meaning":  "Interactive add-on",
        "booking":  true,
        "notes":  "Only worth it if buying bands and spending time in land.",
        "status":  "Active",
        "order":  7,
        "uncertainty":  "Requires separate Power-Up Band purchase for full experience."
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Dark Universe",
        "name":  "Monsters Unchained: The Frankenstein Experiment",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Major dark ride; strong priority.",
        "status":  "Active",
        "order":  8,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Dark Universe",
        "name":  "Curse of the Werewolf",
        "color":  "Orange",
        "meaning":  "Thrill optional",
        "booking":  false,
        "notes":  "Spinning coaster; prioritize if thrill group wants it.",
        "status":  "Active",
        "order":  9,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "Dark Universe",
        "name":  "Meet the Monsters / Darkmoor Atmosphere",
        "color":  "Yellow",
        "meaning":  "If time / atmosphere",
        "booking":  false,
        "notes":  "Good land exploration if not rushing.",
        "status":  "Active",
        "order":  10,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "How to Train Your Dragon - Isle of Berk",
        "name":  "Hiccup\u0027s Wing Gliders",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Family coaster; strong recommendation for most groups.",
        "status":  "Active",
        "order":  11,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "How to Train Your Dragon - Isle of Berk",
        "name":  "Fyre Drill",
        "color":  "Yellow",
        "meaning":  "If time / water play",
        "booking":  false,
        "notes":  "Interactive boat/water attraction; may get wet.",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "How to Train Your Dragon - Isle of Berk",
        "name":  "Dragon Racer\u0027s Rally",
        "color":  "Orange",
        "meaning":  "Thrill optional",
        "booking":  false,
        "notes":  "Physical spinning/flying-style ride; may not be for everyone.",
        "status":  "Active",
        "order":  13,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "How to Train Your Dragon - Isle of Berk",
        "name":  "The Untrainable Dragon",
        "color":  "Green",
        "meaning":  "Must do show",
        "booking":  false,
        "notes":  "Recommended show break; good family pacing.",
        "status":  "Active",
        "order":  14,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "The Wizarding World of Harry Potter - Ministry of Magic",
        "name":  "Harry Potter and the Battle at the Ministry",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Top priority headliner; expect high demand.",
        "status":  "Active",
        "order":  15,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "The Wizarding World of Harry Potter - Ministry of Magic",
        "name":  "Le Cirque Arcanus",
        "color":  "Green",
        "meaning":  "Must do show",
        "booking":  false,
        "notes":  "Good show break and major land experience.",
        "status":  "Active",
        "order":  16,
        "uncertainty":  ""
    },
    {
        "day":  5,
        "park":  "Epic Universe",
        "land":  "The Wizarding World of Harry Potter - Ministry of Magic",
        "name":  "Explore Wizarding Paris",
        "color":  "Yellow",
        "meaning":  "Atmosphere / optional",
        "booking":  false,
        "notes":  "Use for food, shops, spells, and pacing.",
        "status":  "Active",
        "order":  17,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Production Central",
        "name":  "Despicable Me Minion Mayhem",
        "color":  "Yellow",
        "meaning":  "If time / family ride",
        "booking":  false,
        "notes":  "Good for Minions fans; simulator may cause motion sickness.",
        "status":  "Active",
        "order":  1,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Production Central",
        "name":  "TRANSFORMERS: The Ride-3D",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Strong simulator ride; good early target.",
        "status":  "Active",
        "order":  2,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Minion Land",
        "name":  "Illumination\u0027s Villain-Con Minion Blast",
        "color":  "Yellow",
        "meaning":  "If time / interactive",
        "booking":  false,
        "notes":  "Good filler if wait is low.",
        "status":  "Active",
        "order":  3,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Minion Land",
        "name":  "Minion Cafe",
        "color":  "Orange",
        "meaning":  "Food stop",
        "booking":  false,
        "notes":  "Good themed food option if nearby.",
        "status":  "Active",
        "order":  4,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "New York",
        "name":  "Revenge of the Mummy",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Excellent indoor coaster/dark ride; prioritize.",
        "status":  "Active",
        "order":  5,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "New York",
        "name":  "Race Through New York Starring Jimmy Fallon",
        "color":  "Red",
        "meaning":  "Skip",
        "booking":  false,
        "notes":  "Usually lower priority unless fans want it.",
        "status":  "Skip",
        "order":  6,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "San Francisco",
        "name":  "Fast \u0026 Furious: Supercharged",
        "color":  "Red",
        "meaning":  "Skip",
        "booking":  false,
        "notes":  "Low priority; only do if completionist or no wait.",
        "status":  "Skip",
        "order":  7,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "The Wizarding World of Harry Potter - Diagon Alley",
        "name":  "Harry Potter and the Escape from Gringotts",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Major headliner; prioritize.",
        "status":  "Active",
        "order":  8,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "The Wizarding World of Harry Potter - Diagon Alley",
        "name":  "Diagon Alley Exploration",
        "color":  "Green",
        "meaning":  "Must do atmosphere",
        "booking":  false,
        "notes":  "Explore shops, wand areas, dragon, food, and details.",
        "status":  "Active",
        "order":  9,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "The Wizarding World of Harry Potter - Diagon Alley",
        "name":  "Hogwarts Express - King\u0027s Cross Station",
        "color":  "Purple",
        "meaning":  "Park-to-park ticket required",
        "booking":  true,
        "notes":  "Use only if hopping to Islands of Adventure.",
        "status":  "Active",
        "order":  10,
        "uncertainty":  "Requires valid park-to-park admission."
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "World Expo",
        "name":  "Men in Black Alien Attack",
        "color":  "Green",
        "meaning":  "Must do",
        "booking":  false,
        "notes":  "Fun interactive shooter; good repeatable ride.",
        "status":  "Active",
        "order":  11,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Springfield USA",
        "name":  "The Simpsons Ride",
        "color":  "Yellow",
        "meaning":  "If time / fan-dependent",
        "booking":  false,
        "notes":  "Can cause motion sickness; do if Simpsons fans.",
        "status":  "Active",
        "order":  12,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Springfield USA",
        "name":  "Kang \u0026 Kodos\u0027 Twirl \u0027n\u0027 Hurl",
        "color":  "Red",
        "meaning":  "Skip",
        "booking":  false,
        "notes":  "Low-priority spinner.",
        "status":  "Skip",
        "order":  13,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Woody Woodpecker\u0027s KidZone",
        "name":  "E.T. Adventure",
        "color":  "Yellow",
        "meaning":  "Classic / if time",
        "booking":  false,
        "notes":  "Classic dark ride; good low-intensity break.",
        "status":  "Active",
        "order":  14,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Hollywood",
        "name":  "The Bourne Stuntacular",
        "color":  "Green",
        "meaning":  "Must do show",
        "booking":  false,
        "notes":  "Strong indoor show and good rest break.",
        "status":  "Active",
        "order":  15,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Hollywood",
        "name":  "Universal Orlando\u0027s Horror Make-Up Show",
        "color":  "Yellow",
        "meaning":  "If time / older kids",
        "booking":  false,
        "notes":  "Funny show; may be too much for younger kids.",
        "status":  "Active",
        "order":  16,
        "uncertainty":  ""
    },
    {
        "day":  6,
        "park":  "Universal Studios Florida",
        "land":  "Hollywood",
        "name":  "DreamWorks Land",
        "color":  "Yellow",
        "meaning":  "Kids / if time",
        "booking":  false,
        "notes":  "Best for younger kids and character time.",
        "status":  "Active",
        "order":  17,
        "uncertainty":  null
    }
]
;
